  
name: Mirror DOE-NCI-Pilot1-Predictions
on:
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron:  '5 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror
      run: |
        git clone --mirror 'https://github.com/DOE-NCI-Pilot1/Predictions.git'
        cd Predictions.git/
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/adeepsk/DOE-NCI-Pilot1-Predictions.git"
        git push --mirror github
      env:
        GITHUB_TOKEN: ${{ secrets.LEARNING_KEY }}
