name: Mirror NIH.AI-Deep-Learning-Tutorial
on:
  schedule:
    # nightly (0th hour 0th minute of every day)
    - cron:  '*/5 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Mirror
      run: |
        git clone --mirror 'https://github.com/DOE-NCI-Pilot1/NIH.AI-Deep-Learning-Tutorial.git'
        cd NIH.AI-Deep-Learning-Tutorial.git/
        git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/adeepsk/NIH.AI-Deep-Learning-Tutorial.git"
        git push --mirror github
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
